bambora/dev.na.bambora.com

s3-deploy.sh
Need to specify region when syncing master bucket
=> Specify region

source/docs/references/onboarding_API/index.md
=> WEB-567 - updated links to specs

source/layouts/_google_tag_manager.erb, source/layouts/_head.erb
Reverts bambora/dev.na.bambora.com#42
=> Revert "Update Google Tag manager script tags"

source/includes/na/analyze_payments/_overview.md, source/includes/na/save_customer_data/_overview.md
Swapped Analyze Payments and Save Customer Data intro text.
=> Pull content changes into master 

source/docs/guides/merchant_quickstart/Boarding.md, source/docs/references/onboarding_API/index.md
Rebranded and updated links.
This pull request exists so that Misty can take a look at the current pending changes for rebrand.
Please take a careful look at the links and make sure that they are correct.
=> WEB-659: Updating Boarding page to Bambora

README.md, data/na/API_spec/partner/2016-06-11.yaml, data/na/API_spec/partner/2016-08-18.yaml, source/docs/references/onboarding_API/tac_v2016-08-18.erb, source/docs/references/onboarding_API/v2016-08-18.erb, source/layouts/swagger.erb
non-rebrand documentation changes to go out
=> Careless whisper

source/docs/references/onboarding_API/index.md
Editing the changelog to reflect changes and to trigger a rebuild/fetch of the swagger spec from the OnboardingAPI
=> Updates to changelog for WEB-773 and WEB-460

source/docs/guides/merchant_quickstart/calling_APIs.md
New version of Merchant Quickstart Guide 2/3
=> Updated Merchant Quickstart Guide 2/3

source/docs/guides/merchant_quickstart/Boarding.md
Last updated page for the Merchant Quickstart Guide 3/3
=> Update Merchant Quickstart Guide 3/3

source/docs/guides/merchant_quickstart/index.md
Updated Merchant Quickstart Guide 1/3
=> Updated Merchant Quickstart Guide 1/3

source/docs/guides/hosted_payment_form/index.md
My changes to the documentation for the re-branded hosted payment form.
=> Updated Documentation to Checkout

source/docs/guides/apple_pay/index.md
Updated Apple Pay docs. Final update should be pushed to meet the release of Apple Pay on June, 7th.
=> Updated Apple Pay Docs

source/docs/guides/onboarding.md
Updated version of the Onboarding API Guide.
=> Updated Onboarding API Guide

data/na/tocs/payment_apis.yaml, source/docs/references/payment_APIs/payment_profile_response_codes.md, source/docs/references/payment_APIs/test_cards.md
- adding payment profile response codes
- moving test cards to payment api dir
=> Payment profile response codes

source/docs/references/onboarding_API/index.md
A bit of a more detailed change log. Anything else we should add?
=> WEB-804 - changelog updated

data/na/tocs/custom_checkout.yaml, source/docs/guides/custom_checkout/setup.md, source/docs/references/custom_checkout/index.md, source/docs/references/custom_checkout/release_notes.md, source/docs/references/custom_checkout/versions.md
This reverts commit e80944b83a20f6ceeaa1e2170ce2cbb27f2c5906.
=> Revert "Revert "Merge pull request #240 from bambora/WEB-917""

source/docs/guides/masterpass.md, source/docs/guides/visa_checkout.md
Migrating Visa Checkout and Masterpass docs from support.na.bambora.com.
Quick and dirty migration that will need to revisited once we have the querystring API docs published. The speed is required so as not to block the timeline for retiring support.na.bambora.com.
Replacing: 
- https://support.na.bambora.com/bic/w/index.html#docs/masterpass-process-flow.htm%3FTocPath%3DDeveloper%2520Resources%7CMasterPass%2520Process%2520Flow%7C_____1
- https://support.na.bambora.com/bic/w/index.html#docs/visa-checkout-intro.htm%3FTocPath%3DDeveloper%2520Resources%7CVisa%2520Checkout%7C_____0
=> Visa Checkout and Masterpass

source/resources/postman/Bambora.postman_collection.json
@aurorawalker @chris-batt @davidlight77 @Lmasniuk @pzelnip
=> Qo 59 fix postman collection

data/na/swagger/1-0-5.yaml, data/na/tocs/payment_apis.yaml, source/docs/guides/merchant_quickstart/calling_APIs.md, source/docs/references/payment_APIs/index.md, source/docs/references/payment_APIs/v1-0-5.erb, source/includes/na/bank_response_codes/_gateway.md
Reverted merge commits #331 and #330
=> KS Revert PAY-1962

data/na/swagger/1-0-5.yaml, source/docs/guides/merchant_quickstart/calling_APIs.md
Equivalent Pull-Up-Into change to deploy to master.
=> Test (For PAY-2254 / ZOO-929)

source/docs/guides/batch_payment/batch.md, source/docs/guides/batch_payment/index.md
=> ZOO-1395 Update batch guide

source/docs/guides/batch_payment/index.md
=> ZOO-1935 - fix bullet list

.editorconfig, .markdownlint.json, source/docs/guides/onboarding.md, source/docs/references/onboarding_API/index.md
De-linted a few of the Onboarding docs pages, corrected a few typos.
Added a .markdownlint.json file & .editorconfig
=> WEB-1584 cleanup onboarding docs

source/docs/support.md
Adding a link to the release notes page in help.na.bambora.com
=> Add link to release notes

data/na/tocs/support.yaml, source/docs/references/onboarding_API/index.md
Pulling the OAPI changelog change from test -> master
=> Test -> Master

source/docs/guides/onboarding.md, source/docs/references/onboarding_API/index.md
Add required field Average Transaction Amount to PSP-CAD onboarding API workflow 
Add required field Average Time from Purchase to Delivery to PSP-CAD onboarding API workflow
Add required field Are You Seasonal to PSP-CAD onboarding API workflow
=> WEB-1590: update changelog and refs for onboarding > buisness sales flow

source/docs/references/onboarding_API/index.md
@Connorbroadfoot identified a goof in the OAPI changelog, this is just updating that.
=> WEB-1590 correct OAPI changelog for Oct 31

data/na/swagger/1-0-5.yaml, source/docs/guides/payment_profiles.md
This reverts commit dc37ee4be46b9c32425550571023372c35de52f8, reversing
changes made to 67eea4844192e8a9efda4ee3bbd25d94966d5c2b.
=> Revert "Merge pull request #407 from bambora/BAT-2"

data/na/swagger/1-0-5.yaml, source/docs/guides/payment_profiles.md
Reverts:
b18025a6388b3b7e883f8b614a33639f51c98f86
373258a
fcdf755
3c3a767
=> Revert BAT-2 from test

README.md, build_content.sh, s3-deploy.sh
And out of Bamboo.
Note that once this gets merged, we'll have to update the Bamboo build job for testing, and during that time we won't be able to deploy master.
=> OE-231 - Move build scripts into repo

data/na/swagger/1-0-5.yaml, source/docs/guides/payment_profiles.md
This reverts commit 2e543403bdab4b6d3dff62eab22b31f89ec0efb0, reversing
changes made to b18025a6388b3b7e883f8b614a33639f51c98f86.
Ie this is the revert of the revert of commits:
b18025a
373258a
fcdf755
3c3a767
Once you're all ready to have the changes for BAT-2 go live feel free to merge this back into test, do the testing (though presumably this is all stuff that's already been tested), and then into master to deploy.  Thanks!
=> BAT-2 Revert "Merge pull request #419 from bambora/revert-BAT-2-from-test"

data/na/swagger/1-0-5.yaml, source/docs/guides/payment_profiles.md
Update the docs to include the ability to create profiles with a transaction id through the rest api.
=> BAT-104 Update the docs for new REST functionality 

source/docs/guides/merchant_quickstart/Boarding.md
Removed Moneris as an Onboarding Option
=> ZOO-2246: Remove Moneris

Makefile, README.md, data/na/tocs/support.yaml, source/includes/na/collect_card_data/_in_app.md
As the subject reads.
Also added a makefile for running locally.
=> OE-492 fix some dead links

data/na/swagger/1-0-5.yaml
Getting settlement report into the Swagger.
=> OE-596 update API swagger

data/na/swagger/1-0-5.yaml
Getting the settlement report yaml into the mainline.
=> OE-596 - DO NOT MERGE UNTIL October 27th

source/resources/postman/Bambora.postman_collection.json
As the subject reads.
Apologies for the large diff, apparently the collection hasn't been updated in some time and the export switched it from v2.0 to v2.1.
=> OE-646 add settlement report to postman collection
